a=float(input("Enter the first number"))
b=float(input("Enter the second number"))
c=float(input("Enter the third number"))
largest=a if ((a>b)and(a>c)) else (b if (b>c) else c)
print ("the largest number among %d %d %d is %d"%(a,b,c,largest))
